### ISSUE TITLE
Instead of multiple azure cli (bash), would a terraform script be possible?

### ISSUE THREAD

**Issue by gunnars04** [mspnp/aks-baseline#354] opened 2022-10-12 13:33 UTC
Thanks in advance :-)

**Comment by ckittel** [comment] 2022-10-24 18:54
Sure, you can do that.  This reference implementation does not provide any automation, by design.  If you're looking for pre-built automation around this scenario, please see the note on the [Prerequisites page](https://github.com/mspnp/aks-baseline/blob/main/01-prerequisites.md#prerequisites).  I think the team referenced in that note is going to or already has created some Terraform implementations.  I'm going to close the issue, but if you still have a question, let me know.

**Closed by ckittel** 2022-10-24 18:54 UTC

**Comment by anwarchk** [comment] 2022-10-24 20:00
@ckittel Are there any known implementation of this in Terraform that you can point us to ?

**Comment by ckittel** [comment] 2022-10-24 21:10
@anwarchk In the link above, there is a Terraform implementation.  I have no idea how complete/aligned it is, as I stated.
